management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health
      base-path: /
      path-mapping:
        health: healthcheck
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: never

info:
  app:
    version: @project.version@
    name: @project.name@
